import type { NextPage } from 'next';
import Head from 'next/head';
import { Home } from '~/containers';
import styles from '../styles/Home.module.css';

const Index: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>AWS Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home></Home>
    </div>
  );
};

export default Index;
