import type { NextPage } from 'next';
import Head from 'next/head';
import { Home } from '~/page-components';

const Index: NextPage = () => {
  return (
    <div>
      <Head>
        <title>AWS Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home></Home>
    </div>
  );
};

export default Index;
